global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "tmc-server"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets:
          - "host.docker.internal:8080"

  - job_name: "tmc-demo"
    metrics_path: "/actuator/prometheus"
    file_sd_configs:
      - files:
          - "/etc/prometheus/targets/tmc-demo.yml"
        refresh_interval: 30s
